services:
  FEA_API:
    # build: .  -- a command for local building
    image: 'feelmax/fea_api'
    ports:
      - '3001:3001'
  FEA_UI:
    image: 'feelmax/fea_ui'
    ports:
      - '3000:3000'
    depends_on:
      - FEA_API
  # quick selenoid-chrome solution:
  selenoid:
    image: 'selenoid/chrome'
    # network_mode: bridge
    ports:
      - '4444:4444'
    depends_on:
      - FEA_UI
  # classic mode of selenoid with selenoid-ui below
  # selenoid:
  #   network_mode: bridge
  #   image: 'aerokube/selenoid'
  #   volumes:
  #     - "./selenoid_bin:/etc/selenoid"
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #     - "./selenoid_bin/video:/opt/selenoid/video"
  #     - "./selenoid_bin/logs:/opt/selenoid/logs"
  #   environment:
  #     - OVERRIDE_VIDEO_OUTPUT_DIR=/path/to/config/video
  #   command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
  #   ports:
  #     - '4444:4444'
  #   depends_on:
  #     - monolite
  # selenoid-ui:
  #   image: 'aerokube/selenoid-ui'
  #   network_mode: bridge
  #   links:
  #     - selenoid
  #   ports:
  #     - '8080:8080'
  #   command: ["--selenoid-uri", "http://selenoid:4444"]
  #   depends_on:
  #     - selenoid