name: 'Cache data on current job'
description: 'Get the dependencies (via npm) and cache them'
runs:
  using: 'composite'
  steps:
    - name: cache dependencies
      id: cache
      uses: actions/cache@v4
      with:
        path: node-modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: install dependencies
      if: steps.cache.outputs.cache-hit != true
      run: npm ci
      shell: bash
