export const speechList = [
  { dataName: 'verbs', translateName: 'глаголы', color: '#DDA0DD' },
  { dataName: 'phrasal verbs', translateName: 'фразовые глаголы', color: '#FFFF80' },
  { dataName: 'nouns', translateName: 'существительные', color: '#6A90FF' },
  { dataName: 'adjectives', translateName: 'прилагательные', color: '#FFB6C1' },
  { dataName: 'adverbs', translateName: 'наречия', color: '#CE6A5C' },
  { dataName: 'pronouns', translateName: 'местоимения', color: '#CDFF2F' },
  { dataName: 'numerals', translateName: 'числительные', color: '#FFA500' },
  { dataName: 'other parts', translateName: 'прочие части речи', color: '#AFEEEE' },
  { dataName: 'idioms', translateName: 'идиомы', color: '#FFDAB9' },
  { dataName: 'useful phrases', translateName: 'популярные фразы', color: '#9ACD32' },
]

export const domain = 'http://127.0.0.1:3001/api'

export const spinner = `
<div class="d-flex justify-content-center">
  <div class="spinner-border" role="status">
    <span class="visually-hidden">Loading...</span>
  </div>
</div>
`

export const system_colors = {
  success: '#94ff94',
  failed: '#ff8c8c',
}

export const easyTopicList = [
  'What are your hobbies?',
  'How long have you been doing these hobbies, and how did you get started?',
  'What hobbies did you use to have, but now do not?',
  'Do you like reading? Why/why not?',
  'What kind of books do you like?',
  'What was the last book you read?',
  'What types of music do you like/dislike?',
  'What’s your favorite song/album/artist?',
  'What music is popular in your country right now?',
  'What was the last movie you saw? How was it?',
  'What is your favorite movie? Why?',
  'How often do you watch movies in English?',
  'What are some of the greatest technological achievements?',
  'Do you like to have cutting edge technology?',
  'Do you think technological advances are always good? Or can they sometimes be bad and harmful?',
  'What do you do?',
  'What is your dream job?',
  'What are some jobs that you think would be boring for you?',
  'What is your favorite food?',
  'What food comes from your country?',
  'What is the most unusual thing you’ve ever eaten. Did it taste good or bad?',
  'Do you enjoy shopping? Why/why not?',
  'In your city, where is a good place to go shopping?',
  'How do you feel about online shopping?',
  'What is your favorite holiday?',
  'What is your favorite holiday food?',
  'What holidays have disappeared in your country?',
  'Do you play any sports?',
  'What is the most popular sport in your country?',
  'What sport do you think is the most expensive?',
  'How would you describe yourself?',
  'What’s the most important thing I should know about you?',
  'What are you passionate about?',
  'What are the achievements you are most proud of?',
  'What are the most important things to you in life?',
  'What do you really like and dislike to do when you have free time?',
  'Have you tried dangerous hobbies?',
  'How much time do you spend (or want to spend) on your hobby?',
  'What is your favourite food and drink?',
  'Do you follow any specific diet?',
  'What healthy food do you like? How often do you eat unhealthy food?',
  'Do you prefer to eat at home or in a restaurant? Why?',
  'What is the most beautiful place you have ever been to?',
  'How much money do you need to travel Europe?',
  'What is the next book you would like to read?',
  'What is your dream job?',
  'What local events are you looking forward to?',
  'What is the longest book you have ever read?',
  'What’s the best exhibition you have ever been to?',
]

export const middleTopicList = [
  'What kind of expensive hobbies have you heard of? Have you tried some of them?',
  'What type of occupation drives you most?',
  'What dishes foreigners must try in your country?',
  'Can you control your emotions well? How do you do that?',
  'If you’re feeling down, how can you make yourself feel better?',
  'When do you feel most energized? ',
  'Can you explain why feelings could cause someone to commit a crime?',
  'Are women more emotional than men? Or is that just a stereotype?',
  'What’s the worst thing that’s happened to you while traveling?',
  'If you were travelling round the world, which three destinations would be “must sees”?',
  'What do you know about a “culture shock”? ',
  'Do you think global warming is a real threat?',
  'Do you believe that recycling is a necessity?',
  'Are there some ways that would help us to save more water?',
  'What job suits you best in your opinion?',
  'Do you think women and men should be paid equally for the same job?',
  'Do you know of the vacancies more popular with people than some other ones?',
  'Do you love what you do/ your occupation or you are just doing it for the money?',
  'If you had the opportunity to start your own business, what would it be?',
  'What skills would you like to develop as you get older?',
  'Would you prefer to live in the city or in a countryside?',
  'What kind of things would you do if you had more money?',
  'Have you had the same friends most of their life, or made a lot of new ones?',
  'Would you say that I understand your feelings?',
  'What kind of a parent do you think you’d be?',
  'What is the best “relationship advice” someone has ever given you?',
  'What do you believe is true that most people would disagree with you?',
  'Do you think that art is important to society?',
  'What do you think about the museums and art galleries in this area or city? Do you think anything should be done to improve them?',
  'Do you think that the internet and television will eventually make books obsolete?',
  'Describe an interest or hobby that you particularly enjoy.',
  'Talk about the most important benefit of the internet.',
  'Describe a website that you often use.',
  'Describe a beautiful place to visit in your country.',
  'Describe an enjoyable day you spent in the countryside.',
  'Describe your favourite city.',
  'Describe a foreign country you have never been to.',
  'Describe the person in your family who you most admire.',
  'Describe one of your childhood memories.',
  'Describe a family celebration that you remember.',
  'Tell a childhood story you heard when you were a child.',
  'Describe the best gift/ present you have received.',
  'Describe your favorite shop.',
  'Describe an open-air or street market which you enjoyed visiting',
  'Describe a shopping center you often go to',
  'Describe a memorable journey you have made',
  'Describe a journey that you remember well',
  'Describe your idea of a perfect vacation',
  'Describe a hotel you have stayed in.',
  'Describe a school which you went to.',
  'Talk about a subject you are studying',
  'Describe your study room.',
  'Describe a wild animal',
  'Describe your favourite animal',
  'Talk about a pet that you or someone you know once had.',
  'Describe a plant, flower or tree that you like.',
  'Describe a language you would like to learn.',
  'Describe one of your daily life.',
  'Describe a surprise that made you happy.',
  'Describe a newspaper or magazine you enjoy reading.',
  'Describe a special occasion in your life.',
  'Describe a recent event that made you happy.',
  'Describe a life changing experience.',
  'Describe an exciting experience in your life.',
]

export const hardTopicList = [
  'Who is your best friend? Describe this person and say why he or she is your best friend.',
  'What way of getting around do you prefer? Describe it and explain why it is your favorite means of transportation.',
  'What place in your city or town would you recommend to visitors who want to have fun? Describe this place and explain why it is fun.',
  'Name the invention that has changed your life most recently. Explain why it is so.',
  'What is the most impressive moment in your life? Describe it and state the reasons for your choice.',
  'What is your perfect career? Describe what it would look like, what you would do and why it interests you.',
  'Who is your favorite teacher? Name qualities that make him or her such a good teacher for you and give example to support your choice.',
  'Your friend wants to visit a new country. What country would you recommend and why?',
  'What is your favorite place for eating out? Describe the place and explain why you like it.',
  'Choose a famous person who you would like to have a conversation with. Explain your choice giving specific reasons and details.',
  'Talk about a time when you found a job more challenging than you expected. What were you trying to accomplish? Why did it become difficult?',
  'What is your favorite school subject? Explain your choice using details and examples.',
  'Which tradition of your country do you think people in other countries should adopt? Give reasons to support your choice.',
  'Are you more like your mother or father in personality? Give reasons and examples to support your response.',
  'What is your most important possession? Describe it and explain why it is important.',
  'Talk about your favorite style of clothing. Describe it and explain why it is your favorite.',
  'Talk about a positive experience with learning or using English. Describe the experience and explain why it was positive.',
  'What you and your family enjoy doing when you are together? Describe it and say why it is enjoyable for all of you.',
  'Where would you like to live if you could live anywhere? Describe this place and say why you have chosen it.',
  'Talk about the most intelligent person you have ever met. Describe this person and explain why you think she or he is intelligent.',
  'What type of movies do you prefer watching: comedy or drama? Explain your choice by giving details.',
  'What is your favorite place to study? Describe this place and explain why it suits you.',
  'Talk about your country’s national anthem or flag. What is it like? Where is it used and where can it be found? Include details and examples to support your response.',
  'Describe an experience in your life that made you feel embarrassed. Explain why it was embarrassing.',
  'What is your favorite season of the year? Explain what makes you like it.',
  'Name a place in your country you would recommend others to visit. Use details to support your recommendation.',
  'Do you think that the university education is important for all people? Give reasons for your opinion.',
  'Some people prefer to focus on one job throughout their life; others like to change jobs. Which strategy do you think is better? Explain why.',
  'Do you prefer living in a big city or small town? State your preference and give reasons as to why you feel this way.',
  'What is wiser: to save the money you have earned for future expenses or spend it right away on things you enjoy? Give reasons to support your opinion.',
  'Some people prefer to work from home. Others think it is better to work in an office. Which do you choose, and why?',
  'Some people always try to respond to emails and other messages they receive immediately. Others take time to respond. Which do you do, and why?',
  'To what extent do you agree with the following statement? Use details and examples to support your opinion.  It is better for students if they spend more time learning outside of classrooms than in classrooms.',
  'Do you prefer to attend a college or university full-time or part-time? Why is it so? Explain your choice by using details and examples.',
  'Some people prefer to take a long vacation while others prefer to take several short vacations, which do you prefer and why? Include details and examples to support your explanation.',
  'What are the pros and cons for doing volunteer work? Use details and examples to defend your point.',
  'What are the positive and negative sides of English becoming the world language?',
  'Do you think that zoos are generally good or bad? Give reasons to support your opinion.',
  'Some people think that cell phones should be prohibited in schools. Do you support or oppose this opinion? Explain why.',
  'Should new university students all be required to read the same book in the summer before they start their first course of study? Explain your response.',
  'Some people prefer to be self-employed, while others find that working for someone else is better for them. Which side do you take and why?',
  'Do innovations and technology make our lives simpler or more complex? Use details and examples to support your answer.',
  'What in your opinion is more effective: learning on your own or learning with a teacher? Support your response with reasons and examples.',
  'Do you think that prohibition of smoking in public places is a good idea? Explain why you think so.',
  'Would you agree or disagree that young people have nothing to teach older people? Support your opinion by giving details and examples.',
  'Do you agree or disagree with people who believe that life is about relaxing instead of hurrying? Use details and examples to illustrate your opinion.',
  'Do you think that celebrities must set a good example for young people? Give reasons to support your opinion.',
  'Some people think it is important  for neighbors to know each other. Others believe it is not so important to have social interactions with neighbors. Which do you agree with, and why?',
  'Would you agree or disagree with the following statement? Give reasons in support of your argument. It is very important for the government to fund the arts.',
  'More and more people choose online education. What is your opinion on this type of learning? Give details and examples to support your response.',
  'Do you agree or disagree with this statement: Teachers should be evaluated by their students? Support your argument with examples and details.',
  'If you were convicted of a murder, would you prefer the death sentence or life in prison? Give reasons to support your argument.',
  'Some educators believe that grades encourage students to learn. Others find using grades controversial or even harmful. What is your stance on this matter and why?',
  'Among all existing alternative energy sources, which one of them would you choose and why/ what are the reasons?',
  'Describe a situation where you had to communicate in a foreign language for the first time.',
  'Describe some advice you received (from your friend or family member) which was useful to you.',
  'Describe a time when you were asked to give your opinion in a questionnaire or survey.',
  'Describe a piece of local news that was interesting to you.',
  'Describe a leader or politician who you admire.',
  'Describe a piece of art (a painting, drawing, sculpture or decorative object) that you like.',
  'Is ageism the new racism?',
  'Deprivation of health care: Dealing with consequences.',
  'Are convicts still punished after serving time?',
  'Are labor laws fair?',
  'How is society viewing domestic violence towards men?',
  'Discrimination against pregnant women.',
  'Fat shaming in the job market.',
  'Overcoming poverty-based discrimination in our society.',
  'Do recovering addicts deal with social injustice?',
  'Are Arabs and Middle Easterners subject to discrimination?',
  'Refugees across the world.',
  'Building a wall between Mexico and the US.',
  'What are the factors behind illegal immigration?',
  'Children of war.',
  'How do the economics of war affect society?',
  'Who paid the price for the War on Terrorism?',
  'Role of women in war.',
  'Role of media in wartime.',
  'Legalizing abortion: the effect on the birth rate and marriage',
  'Should museums in Europe return ancient artifacts home?',
  'Social movements in the modern society: a human rights perspective',
  'How can businesses influence consumption trends?',
  'Children and consumption of fast food.',
  'Sustainable consumption of meat and fish: Its effect on the environment.',
  'Consumption of alcohol.',
]
