name: api testing workflow
on: 
  push:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: get access to repository code
        uses: taiki-e/checkout-action@v1
      - name: cache dependencies
        uses: actions/cache@v4
          with:
            path: ~/.npm
            key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: install dependencies
        run: npm ci
      - name: linting code
        run: echo code is linting...
  api-test:
    needs: lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./source
    steps:
      - name: get access to repository code
        uses: taiki-e/checkout-action@v1
      - name: cache dependencies
        uses: actions/cache@v4
          with:
            path: ~/.npm
            key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: install dependencies
        run: npm ci
      - name: run api tests
        run: npm run api-test
