name: Test eng application
on:
  workflow_dispatch:
  push:
  pull_request:
    types: [opened, edited, reopened]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: get access to repository code
        uses: taiki-e/checkout-action@v1
      - name: install dependencies
        run: npm ci
      - name: linting code
        run: echo code linting...
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: get access to repository code
        uses: taiki-e/checkout-action@v1
      - name: install dependencies
        run: npm ci
      - name: up stand
      - run: npm run dev_api
      - run: npm run dev
      - run: npm run ui_tests
